### ISSUE TITLE
Dashboard Projet : problème dans "onglet matière" de "détail d'une pièce"

### ISSUE THREAD

**Issue by mmclaret** [mmclaret/WINDEV#35]
La case de "En stock" est déjà cochée par défaut lorsqu'on passe l'article en production depuis une offre de prix.
Est-ce normal? Il ne devrait également pas y avoir de Tick à côté de "Matière traitée".
![2016-05-06_094342](https://cloud.githubusercontent.com/assets/18596991/15074812/09c970a2-136f-11e6-813b-51e0c26aaa19.jpg)

**Comment by fpclaret** [comment]
L'affichage ne se fait pas auto apres ajout matiere
