### ISSUE TITLE
Export fichier PDF : Par défaut, ouvrir l'emplacement du projet lors de l'export d'un fichier PDF

### ISSUE THREAD

**Issue by mmclaret** [mmclaret/WINDEV#58]
L'appliquer pour ces exports : 
- soumission   ¦   dossier par défaut : #projet/10. Achats/1. Soumissions
- bon de commande   ¦   dossier par défaut : #projet/10. Achats/2. Commandes
- bon de livraison   ¦   dossier par défaut : #projet

Réutilisé la façon de faire pour les export d'offre de prix.

**Comment by fpclaret** [comment]
Ouvre le dossier numéro de projet. Le dossier "Achats" n'a pas toujours le même numéro (parfois "10. Achats", "11. Achats" ou "12. Achats")

**Comment by mmclaret** [comment]
Par défaut c'est "12. Achats".
C'est possible d'aller dans ce dossier si le "12. Achat" existe, et s'il n'existe pas aller dans le numéro de projet?
