### ISSUE TITLE
Réception de commande : manque 1 item sur la liste des items d'un PO à réceptioner

### ISSUE THREAD

**Issue by mmclaret** [mmclaret/WINDEV#97]
Des fois il manque un item, qui ne s'affiche pas lorsque l'on fait une recherche par PO pour le réceptionner.

Dernier exemple : 8885. 5 items de commandés, mais en faisant une recherche par PO pour les réceptionner, seulement 4 sortaient dans le tableau. L'item manquant ne peut pas être réceptionné.

**Comment by fpclaret** [comment]
Je n'ai pas le problème, à voir mardi.

**Comment by mmclaret** [comment]
Le problème vient d'apparaître à nouveau. Aucune différence identifiable au niveau des items.
2 item de commandé sur le PO8979. Lorsque que l'on va pour réceptionner pour la 1ère fois, seulement 1 des 2 items apparaissait.

Par contre, les 2 items apparaissaient bien lorsque l'on affichait tous les items à réceptionner. C'est d'ailleurs grâce à ça qu'on a quand même pu réceptionner les 2 items.
